// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
// 判断当前是否在执行 migrate 命令
const isMigration = process.argv.some((arg) => arg.includes("migrate"));
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: isMigration
      ? process.env["POSTGRES_URL_NON_POOLING"]
      : process.env["POSTGRES_URL"],
  },
});
