/**
 * 审计操作命名规范：{domain}:{action}
 * - 全小写，中划线分隔单词
 * - 前端通过 AUDIT_OP_LABEL 映射展示
 */
export const AUDIT_OP = {
    // ========== 认证 ==========
    AUTH_LOGIN: "auth:login",
    AUTH_LOGOUT: "auth:logout",
    AUTH_REFRESH: "auth:refresh",
    AUTH_REGISTER: "auth:register",
    AUTH_CHANGE_PWD: "auth:change-password",
    AUTH_RESET_PWD: "auth:reset-password",
    AUTH_CANCEL_ACCOUNT: "auth:cancel-account",
    AUTH_SWITCH_TENANT: "auth:switch-tenant",
    // ========== 审批 ==========
    APPROVAL_SUBMIT: "approval:submit",
    APPROVAL_APPROVE: "approval:approve",
    APPROVAL_REJECT: "approval:reject",
    APPROVAL_RESUBMIT: "approval:resubmit",
    // ========== 用户 ==========
    USER_CREATE: "user:create",
    USER_UPDATE: "user:update",
    USER_DELETE: "user:delete",
    USER_BATCH_DELETE: "user:batch-delete",
    USER_RESET_PWD: "user:reset-password",
    USER_ASSIGN_ROLE: "user:assign-role",
    USER_ASSIGN_DEPT: "user:assign-dept",
    USER_VIEW_SENSITIVE: "user:view-sensitive",
    USER_IMPORT: "user:import",
    USER_EXPORT: "user:export",
    // ========== 角色 ==========
    ROLE_CREATE: "role:create",
    ROLE_UPDATE: "role:update",
    ROLE_DELETE: "role:delete",
    ROLE_ASSIGN_MENU: "role:assign-menu",
    ROLE_ASSIGN_PERM: "role:assign-permission",
    ROLE_ASSIGN_USER: "role:assign-user",
    ROLE_ASSIGN_DEPT: "role:assign-dept",
    // ========== 权限 ==========
    PERM_CREATE: "permission:create",
    PERM_UPDATE: "permission:update",
    PERM_DELETE: "permission:delete",
    // ========== 通知 ==========
    NOTICE_CREATE: "notice:create",
    NOTICE_UPDATE: "notice:update",
    NOTICE_DELETE: "notice:delete",
    NOTICE_PUBLISH: "notice:publish",
    NOTICE_REVOKE: "notice:revoke",
    NOTICE_TEMPLATE_CREATE: "notice-template:create",
    NOTICE_TEMPLATE_UPDATE: "notice-template:update",
    NOTICE_TEMPLATE_TEST: "notice-template:test-send",
    NOTICE_CHANNEL_UPSERT: "notice-channel:upsert",
    NOTICE_CHANNEL_DELETE: "notice-channel:delete",
    // ========== 系统配置 ==========
    SETTINGS_SITE_UPDATE: "settings:site-update",
    SETTINGS_PWD_POLICY_UPDATE: "settings:password-policy-update",
    SETTINGS_UPLOAD_UPDATE: "settings:upload-update",
    // ========== 租户 ==========
    TENANT_CREATE: "tenant:create",
    TENANT_UPDATE: "tenant:update",
    TENANT_DELETE: "tenant:delete",
    TENANT_IMPORT: "tenant:import",
    TENANT_EXPORT: "tenant:export",
    // ========== 部门 / 菜单 / 字典 ==========
    DEPT_CREATE: "dept:create",
    DEPT_UPDATE: "dept:update",
    DEPT_DELETE: "dept:delete",
    MENU_CREATE: "menu:create",
    MENU_UPDATE: "menu:update",
    MENU_DELETE: "menu:delete",
    DICT_TYPE_CREATE: "dict-type:create",
    DICT_DATA_CREATE: "dict-data:create",
    // ========== 缓存 / 监控 ==========
    CACHE_CLEAR_GROUP: "cache:clear-group",
    CACHE_DELETE_KEY: "cache:delete-key",
    JOB_RUN_ONCE: "job:run-once",
    JOB_TOGGLE_STATUS: "job:toggle-status",
    JOB_PAUSE: "job:pause",
    JOB_RESUME: "job:resume",
    JOB_LOG_CLEAR: "job-log:clear",
    // ========== IP 规则 ==========
    IP_RULE_CREATE: "ip-rule:create",
    IP_RULE_UPDATE: "ip-rule:update",
    IP_RULE_DELETE: "ip-rule:delete",
    IP_RULE_CHECK: "ip-rule:check",
    // ========== 文件 ==========
    FILE_UPLOAD: "file:upload",
    FILE_DELETE: "file:delete",
    FILE_MERGE: "file:merge",
    FILE_CANCEL: "file:cancel",
    // ========== 在线用户 ==========
    ONLINE_KICK: "online:kick",
    ONLINE_KICK_ALL: "online:kick-all",
    // ========== 审计 ==========
    AUDIT_DAILY_AGGREGATE: "audit-daily:aggregate",
    AUDIT_DAILY_CLEAN: "audit-daily:clean",
};
/** operation → 中文标签（用于展示） */
export const AUDIT_OP_LABEL = {
    [AUDIT_OP.AUTH_LOGIN]: "用户登录",
    [AUDIT_OP.AUTH_LOGOUT]: "用户登出",
    [AUDIT_OP.AUTH_REFRESH]: "刷新令牌",
    [AUDIT_OP.AUTH_REGISTER]: "用户注册",
    [AUDIT_OP.AUTH_CHANGE_PWD]: "修改密码",
    [AUDIT_OP.AUTH_RESET_PWD]: "重置密码",
    [AUDIT_OP.AUTH_CANCEL_ACCOUNT]: "提交注销申请",
    [AUDIT_OP.AUTH_SWITCH_TENANT]: "切换租户",
    [AUDIT_OP.APPROVAL_SUBMIT]: "提交审批申请",
    [AUDIT_OP.APPROVAL_APPROVE]: "审批通过",
    [AUDIT_OP.APPROVAL_REJECT]: "审批驳回",
    [AUDIT_OP.APPROVAL_RESUBMIT]: "重新提交审批",
    [AUDIT_OP.USER_CREATE]: "创建用户",
    [AUDIT_OP.USER_UPDATE]: "更新用户",
    [AUDIT_OP.USER_DELETE]: "删除用户",
    [AUDIT_OP.USER_BATCH_DELETE]: "批量删除用户",
    [AUDIT_OP.USER_RESET_PWD]: "重置用户密码",
    [AUDIT_OP.USER_ASSIGN_ROLE]: "分配用户角色",
    [AUDIT_OP.USER_ASSIGN_DEPT]: "分配用户部门",
    [AUDIT_OP.USER_VIEW_SENSITIVE]: "查看用户敏感信息",
    [AUDIT_OP.USER_IMPORT]: "导入用户",
    [AUDIT_OP.USER_EXPORT]: "导出用户",
    [AUDIT_OP.ROLE_CREATE]: "创建角色",
    [AUDIT_OP.ROLE_UPDATE]: "更新角色",
    [AUDIT_OP.ROLE_DELETE]: "删除角色",
    [AUDIT_OP.ROLE_ASSIGN_MENU]: "分配角色菜单",
    [AUDIT_OP.ROLE_ASSIGN_PERM]: "分配角色权限",
    [AUDIT_OP.ROLE_ASSIGN_USER]: "分配角色用户",
    [AUDIT_OP.ROLE_ASSIGN_DEPT]: "分配角色数据权限",
    [AUDIT_OP.PERM_CREATE]: "创建权限",
    [AUDIT_OP.PERM_UPDATE]: "更新权限",
    [AUDIT_OP.PERM_DELETE]: "删除权限",
    [AUDIT_OP.NOTICE_CREATE]: "创建通知",
    [AUDIT_OP.NOTICE_UPDATE]: "更新通知",
    [AUDIT_OP.NOTICE_DELETE]: "删除通知",
    [AUDIT_OP.NOTICE_PUBLISH]: "发布通知",
    [AUDIT_OP.NOTICE_REVOKE]: "撤回通知",
    [AUDIT_OP.NOTICE_TEMPLATE_CREATE]: "创建消息模板",
    [AUDIT_OP.NOTICE_TEMPLATE_UPDATE]: "更新消息模板",
    [AUDIT_OP.NOTICE_TEMPLATE_TEST]: "测试发送消息模板",
    [AUDIT_OP.NOTICE_CHANNEL_UPSERT]: "保存通知渠道",
    [AUDIT_OP.NOTICE_CHANNEL_DELETE]: "删除通知渠道",
    [AUDIT_OP.SETTINGS_SITE_UPDATE]: "更新网站信息",
    [AUDIT_OP.SETTINGS_PWD_POLICY_UPDATE]: "更新密码策略",
    [AUDIT_OP.SETTINGS_UPLOAD_UPDATE]: "更新上传配置",
    [AUDIT_OP.TENANT_CREATE]: "创建租户",
    [AUDIT_OP.TENANT_UPDATE]: "更新租户",
    [AUDIT_OP.TENANT_DELETE]: "删除租户",
    [AUDIT_OP.TENANT_IMPORT]: "导入租户",
    [AUDIT_OP.TENANT_EXPORT]: "导出租户",
    [AUDIT_OP.DEPT_CREATE]: "创建部门",
    [AUDIT_OP.DEPT_UPDATE]: "更新部门",
    [AUDIT_OP.DEPT_DELETE]: "删除部门",
    [AUDIT_OP.MENU_CREATE]: "创建菜单",
    [AUDIT_OP.MENU_UPDATE]: "更新菜单",
    [AUDIT_OP.MENU_DELETE]: "删除菜单",
    [AUDIT_OP.DICT_TYPE_CREATE]: "创建字典类型",
    [AUDIT_OP.DICT_DATA_CREATE]: "创建字典数据",
    [AUDIT_OP.CACHE_CLEAR_GROUP]: "清空缓存组",
    [AUDIT_OP.CACHE_DELETE_KEY]: "删除缓存键",
    [AUDIT_OP.JOB_RUN_ONCE]: "手动执行任务",
    [AUDIT_OP.JOB_TOGGLE_STATUS]: "启停任务",
    [AUDIT_OP.JOB_PAUSE]: "暂停任务",
    [AUDIT_OP.JOB_RESUME]: "恢复任务",
    [AUDIT_OP.JOB_LOG_CLEAR]: "清空任务日志",
    [AUDIT_OP.IP_RULE_CREATE]: "创建 IP 规则",
    [AUDIT_OP.IP_RULE_UPDATE]: "更新 IP 规则",
    [AUDIT_OP.IP_RULE_DELETE]: "删除 IP 规则",
    [AUDIT_OP.IP_RULE_CHECK]: "检查 IP 规则",
    [AUDIT_OP.FILE_UPLOAD]: "上传文件",
    [AUDIT_OP.FILE_DELETE]: "删除文件",
    [AUDIT_OP.FILE_MERGE]: "合并分片",
    [AUDIT_OP.FILE_CANCEL]: "取消上传任务",
    [AUDIT_OP.ONLINE_KICK]: "强制下线",
    [AUDIT_OP.ONLINE_KICK_ALL]: "全部下线",
    [AUDIT_OP.AUDIT_DAILY_AGGREGATE]: "手动聚合审计",
    [AUDIT_OP.AUDIT_DAILY_CLEAN]: "清理审计日报",
};
/** 反查：{domain}:{action} → label */
export function getAuditLabel(operation) {
    return AUDIT_OP_LABEL[operation] ?? operation;
}
//# sourceMappingURL=audit.js.map